kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway-utilitarios-deployment
  labels:
    app: gateway-utilitarios
  namespace: utilitarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-utilitarios
  template:
    metadata:
      labels:
        app: gateway-utilitarios
    spec:
      containers:
        - name: gateway-utilitarios
          image: elturcofarid/gateway-utilitarios
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "20Mi"
              cpu: "100m"
            limits:
              memory: "30Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-utilitarios-service
  labels:
    app: gateway-utilitarios
  namespace: utilitarios
spec:
  type: LoadBalancer
  selector:
    app: gateway-utilitarios
  ports:
    - protocol: TCP
      port: 8080
